#! /usr/bin/env bash

make clean
make

if [ $? -ne 0 ]
then
	echo "Compilaton Problems"
	exit 1
fi

echo "*****TestA*****"
./testharnessm clike TestingMIPS/TestA
# echo "*****TestB*****"
# ./testharnessm clike TestingMIPS/TestB


