#! /usr/bin/env bash

make clean
make

if [ $? -ne 0 ]
then
	echo "Compilaton Problems"
	exit 1
fi

echo "*****Legal Cases*****"
./testharness clike Testing/Legal
echo "*****Illegal Cases*****"
./testharness clike Testing/Illegal


